;1、域名组

ruleset=🇨🇳 优先国内,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Direct.list
ruleset=🐳 Docker,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Docker.list
ruleset=🤖 AI,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/AI.list
ruleset=🐙 GitHub,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list
ruleset=🎶 TikTok,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list
ruleset=📺 YouTube,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/YouTube.list
ruleset=🔎 Google,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list
ruleset=💬 Social,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Social-Oversea.list
ruleset=🍎 Apple,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list
ruleset=🎬 流媒体,https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.list
ruleset=🎮 游戏,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Game.list
ruleset=🌍 国外,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Proxy.list
ruleset=🌍 国外,https://raw.githubusercontent.com/951151045/Hi-openclash/refs/heads/main/clash-main/Global.list
ruleset=🌌 未知归宿,[]FINAL

;2、策略组（域名组-节点组）

custom_proxy_group=🇨🇳 优先国内`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🐳 Docker`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🤖 AI`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🐙 GitHub`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🎶 TikTok`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=📺 YouTube`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🔎 Google`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=💬 Social`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🍎 Apple`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🎬 流媒体`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🎮 游戏`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🌍 国外`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT
custom_proxy_group=🌌 未知归宿`select`[]DIRECT`[]🌟 钦定`[]🐳 Docker专用-自动`[]🤖 AI专用-自动`[]🐙 GitHub专用-自动`[]🎶 TikTok专用-自动`[]📺 YouTube专用-自动`[]🔎 Google专用-自动`[]💬 Social专用-自动`[]🍎 Apple专用-自动`[]♻️ 所有-自动`[]REJECT

;3、节点组

custom_proxy_group=🌟 钦定`select`.*
custom_proxy_group=🐳 Docker专用-自动`url-test`.*`https://production.cloudflare.docker.com`300,50
custom_proxy_group=🤖 AI专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🐙 GitHub专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🎶 TikTok专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=📺 YouTube专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🔎 Google专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=💬 Social专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=🍎 Apple专用-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150
custom_proxy_group=♻️ 所有-自动`url-test`.*`http://www.gstatic.com/generate_204`60,150

;4、启用规则集

enable_rule_generator=true
overwrite_original_rules=true
